server:
  port: 9090

spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.63.58:3306/projex?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: lgh000510
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath*:com/**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名自动识别配置
